# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/cricket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 0, 721, 101))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.batsmen = QtWidgets.QLabel(self.frame)
        self.batsmen.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.batsmen.setFont(font)
        self.batsmen.setObjectName("batsmen")
        self.bowlers = QtWidgets.QLabel(self.frame)
        self.bowlers.setGeometry(QtCore.QRect(170, 50, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bowlers.setFont(font)
        self.bowlers.setObjectName("bowlers")
        self.allrounder = QtWidgets.QLabel(self.frame)
        self.allrounder.setGeometry(QtCore.QRect(330, 50, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.allrounder.setFont(font)
        self.allrounder.setObjectName("allrounder")
        self.wicket = QtWidgets.QLabel(self.frame)
        self.wicket.setGeometry(QtCore.QRect(500, 50, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.wicket.setFont(font)
        self.wicket.setObjectName("wicket")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 30, 701, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.batcount = QtWidgets.QLabel(self.frame)
        self.batcount.setGeometry(QtCore.QRect(110, 50, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.batcount.setFont(font)
        self.batcount.setObjectName("batcount")
        self.bowlcount = QtWidgets.QLabel(self.frame)
        self.bowlcount.setGeometry(QtCore.QRect(270, 50, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bowlcount.setFont(font)
        self.bowlcount.setObjectName("bowlcount")
        self.allcount = QtWidgets.QLabel(self.frame)
        self.allcount.setGeometry(QtCore.QRect(440, 50, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.allcount.setFont(font)
        self.allcount.setObjectName("allcount")
        self.wcount = QtWidgets.QLabel(self.frame)
        self.wcount.setGeometry(QtCore.QRect(640, 50, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.wcount.setFont(font)
        self.wcount.setObjectName("wcount")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(50, 110, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pointcount = QtWidgets.QLabel(self.centralwidget)
        self.pointcount.setGeometry(QtCore.QRect(160, 110, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pointcount.setFont(font)
        self.pointcount.setObjectName("pointcount")
        self.pointuse = QtWidgets.QLabel(self.centralwidget)
        self.pointuse.setGeometry(QtCore.QRect(530, 110, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pointuse.setFont(font)
        self.pointuse.setObjectName("pointuse")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(450, 110, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.player = QtWidgets.QListWidget(self.centralwidget)
        self.player.setGeometry(QtCore.QRect(50, 190, 331, 351))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.player.setFont(font)
        self.player.setObjectName("player")
        self.select = QtWidgets.QListWidget(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(450, 190, 311, 351))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.select.setFont(font)
        self.select.setObjectName("select")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 150, 331, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bat = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.bat.setEnabled(False)
        self.bat.setObjectName("bat")
        self.horizontalLayout.addWidget(self.bat)
        self.bow = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.bow.setEnabled(False)
        self.bow.setObjectName("bow")
        self.horizontalLayout.addWidget(self.bow)
        self.ar = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.ar.setEnabled(False)
        self.ar.setObjectName("ar")
        self.horizontalLayout.addWidget(self.ar)
        self.wk = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.wk.setEnabled(False)
        self.wk.setObjectName("wk")
        self.horizontalLayout.addWidget(self.wk)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(450, 150, 311, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.tname = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tname.setFont(font)
        self.tname.setText("")
        self.tname.setObjectName("tname")
        self.horizontalLayout_2.addWidget(self.tname)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        self.actionSAVE_Team = QtWidgets.QAction(MainWindow)
        self.actionSAVE_Team.setObjectName("actionSAVE_Team")
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        self.menu.addAction(self.actionNEW_Team)
        self.menu.addSeparator()
        self.menu.addAction(self.actionOPEN_Team)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSAVE_Team)
        self.menu.addSeparator()
        self.menu.addAction(self.actionEVALUATE_Team)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket"))
        self.label.setText(_translate("MainWindow", "Your Selections"))
        self.batsmen.setText(_translate("MainWindow", "Batsmen (BAT)"))
        self.bowlers.setText(_translate("MainWindow", "Bowlers (BOW)"))
        self.allrounder.setText(_translate("MainWindow", "Allrounder (AR)"))
        self.wicket.setText(_translate("MainWindow", "Wicker-Keeper (WK)"))
        self.batcount.setText(_translate("MainWindow", "##"))
        self.bowlcount.setText(_translate("MainWindow", "##"))
        self.allcount.setText(_translate("MainWindow", "##"))
        self.wcount.setText(_translate("MainWindow", "##"))
        self.label_10.setText(_translate("MainWindow", "Point Available :"))
        self.pointcount.setText(_translate("MainWindow", "####"))
        self.pointuse.setText(_translate("MainWindow", "####"))
        self.label_13.setText(_translate("MainWindow", "Point Used :"))
        self.bat.setText(_translate("MainWindow", "BAT"))
        self.bow.setText(_translate("MainWindow", "BOW"))
        self.ar.setText(_translate("MainWindow", "AR"))
        self.wk.setText(_translate("MainWindow", "WK"))
        self.label_15.setText(_translate("MainWindow", "Team Name :"))
        self.menu.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "OPEN Team"))
        self.actionSAVE_Team.setText(_translate("MainWindow", "SAVE Team"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
